fcs.text.primary.required.keywords<-function(){
  c(
  '$BEGINANALYSIS',
  '$BEGINDATA',
  '$BEGINSTEXT',
  '$BYTEORD',
  '$DATATYPE',
  '$ENDANALYSIS',
  '$ENDDATA',
  '$ENDSTEXT',
  '$MODE',
  '$NEXTDATA'
)
}
